language: cpp

before_install:
- sudo apt update -qq
- sudo apt install nasm -qq
- sudo apt install xorriso -qq
- sudo apt install gcc-multilib g++-multilib -qq
- sudo apt install grub-pc-bin -qq
- sudo apt install cmake
- git clone git://git.cryptomilk.org/projects/cmocka.git
- cd cmocka
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=ON ..
- sudo make install
- cd ..


script:
- make iso

testing:
- gcc test/test.c -lcmocka -o test
- ./test   
